<?php include("lightml.php") ?>
<html>
<head>
  <meta charset=utf-8">
  <title>Test</title>
</head>
<body>
  <h1>Here are all the HTML5 elements</h1>
  <br>
  <a href="" onclick="alert(1)">a</a>
  <br>
  <abbr title="abbreviation" contenteditable>abbr</abbr>
  <br>
  <address>address</address>
  <br>
  <area>
  <br>
  <article id="toto" class="tata">article</article>
  <br>
  <aside>aside</aside>
  <br>
  <audio> </audio>
  <br>
  <b>b</b>
  <br>
  <base>
  <br>
  <bb>bb</bb>
  <br>
  <bdi>bdi</bdi>
  <br>
  <bdo data-myattr="toto">bdo</bdo>
  <br>
  <blockquote>blockquote</blockquote>
  <br>
  <button>button</button>
  <br>
  <canvas>canvas</canvas>
  <br>
  <cite>cite</cite>
  <br>
  <code>code</code>
  <br>
  <command>
  <br>
  <data>data</data>
  <br>
  <datagrid>datagrid</datagrid>
  <br>
  <datalist>datalist</datalist>
  <br>
  <dd>dd</dd>
  <br>
  <del>del</del>
  <br>
  <details>details</details>
  <br>
  <dfn>dfn</dfn>
  <br>
  <div>div</div>
  <br>
  <dl>dl</dl>
  <br>
  <dt>dt</dt>
  <br>
  <em>em</em>
  <br>
  <embed>
  <br>
  <eventsource>eventsource</eventsource>
  <br>
  <fieldset>fieldset</fieldset>
  <br>
  <figure>
    <figcaption>figure figcaption</figcaption>
  </figure>
  <br>
  <footer>footer</footer>
  <br>
  <form>form</form>
  <br>
  <h1>h1</h1>
  <br>
  <h2>h2</h2>
  <br>
  <h3>h3</h3>
  <br>
  <h4>h4</h4>
  <br>
  <h5>h5</h5>
  <br>
  <h6>h6</h6>
  <br>
  <header>header</header>
  <br>
  <hgroup>hgroup</hgroup>
  <br>
  <hr>
  <br>
  <i>i</i>
  <br>
  <iframe>iframe</iframe>
  <br>
  <img src="//placehold.it/200x200">
  <br>
  <input>
  <br>
  <ins>ins</ins>
  <br>
  <kbd>kbd</kbd>
  <br>
  <keygen>
  <br>
  <label>label</label>
  <br>
  <legend>legend</legend>
  <br>
  <mark>mark</mark>
  <br>
  <map>map</map>
  <br>
  <menu>menu</menu>
  <br>
  <meter>meter</meter>
  <br>
  <nav>nav</nav>
  <br>
  <noscript>noscript</noscript>
  <br>
  <object>object</object>
  <br>
  <ol>ol</ol>
  <br>
  <optgroup>optgroup</optgroup>
  <br>
  <output>output</output>
  <br>
  <p>p</p>
  <br>
  <param>
  <br>
  <pre>pre</pre>
  <br>
  <progress>progress</progress>
  <br>
  <q>q</q>
  <br>
  <ruby>
    ruby
    <rp>rp</rp>
    <rt>rt</rt>
  </ruby>
  <br>
  <s>s</s>
  <br>
  <samp>samp</samp>
  <br>
  <script>"script"</script>
  <br>
  <section>section</section>
  <br>
  <select>
    <option>select option</option>
  </select>
  <br>
  <small>small</small>
  <br>
  <source>
  <br>
  <span>span</span>
  <br>
  <strong>strong</strong>
  <br>
  <style>style</style>
  <br>
  <sub>sub</sub>
  <br>
  <summary>summary</summary>
  <br>
  <sup>sup</sup>
  <br>
  <table>
    <caption>caption</caption>
    <colgroup>
      <col></col>
    </colgroup>
    <thead>
      <tr>
        <th>table thead tr th</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>tbody td</td>
      </tr>
    </tbody>
    <tfoot>
      <td>tfoot td</td>
    </tfoot>
  </table>
  <br>
  <textarea>textarea</textarea>
  <br>
  <time>time</time>
  <br>
  <track>
  <br>
  <u>u</u>
  <br>
  <ul>
    <li>ul li</li>
  </ul>
  <br>
  <var>var</var>
  <br>
  <video>video</video>
  <br>
  <wbr>
</body>
</html>